import type { Metadata } from "next";
import "./globals.css";
import InfoHeader from "@/components/InfoHeader";
import Navbar from "@/components/Navbar";
import GoToTop from "@/components/GoToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth scrollbar">
      <body className=" bg-black">
        <InfoHeader />
        <GoToTop />
        <Navbar />
        <main className="overflow-hidden relative">
        {children}
        </main>
      </body>
    </html>
  );
}
